import numpy as np

In [14]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
print(f"Array mat1D : {mat1D}")
print(f"Array mat1D + 10 {mat1D + 10}")
print(f"Array mat1D indeks ke 2 :{mat1D[2]}")    

Array mat1D : [1 2 3 4 5 6 7 8 9]
Array mat1D + 10 [11 12 13 14 15 16 17 18 19]
Array mat1D indeks ke 2 :3


In [18]:
mat2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"Array mat2D : {mat2D}")
print(f"Array mat2D + 10: {mat2D + 10}")
print(f"Array mat2D indeks ke 2 : {mat2D[2]}")
print(f"Array mat2D indeks ke 2 : {mat2D[1][1] * 10}")

Array mat2D : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array mat2D + 10: [[11 12 13]
 [14 15 16]
 [17 18 19]]
Array mat2D indeks ke 2 : [7 8 9]
Array mat2D indeks ke 2 : 50


In [19]:
print(mat1D.shape)
print(mat2D.shape)

(9,)
(3, 3)


In [20]:
print(mat1D.size)
print(mat2D.size)

9
9


In [37]:
#special matriks
mZero = np.zeros((3,5))
mOne = np.ones((4,4))
mIdentity = np.eye((5))
mFull = np.full((3,3),10)
mF1Random = np.random.rand(5,)
mF2Random = np.random.rand(5,5)
mI1Random = np.random.randint(10,100,size = 10)
mI2Random = np.random.randint(1,100,size = (4,4))
print(f"Matriks mOne :\n {mOne}")
print(f"Matriks mZero :\n {mZero}")
print(f"Matriks mIdentity:\n {mIdentity}")
print(f"matriks mFull:\n {mFull}")
print(f"matriks mF1Random:\n {mF1Random}")
print(f"matriks mF2Random:\n {mF2Random}")
print(f"matriks mI1Random:\n {mI1Random}")
print(f"matriks mI2Random:\n {mI2Random}")

Matriks mOne :
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matriks mZero :
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriks mIdentity:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
matriks mFull:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
matriks mF1Random:
 [0.04495351 0.99186208 0.45968334 0.43696071 0.13991534]
matriks mF2Random:
 [[0.88544627 0.6361792  0.69168912 0.31543234 0.64074097]
 [0.65420262 0.46027682 0.24768359 0.29013698 0.64798934]
 [0.89532049 0.2239054  0.26780535 0.30662332 0.1212861 ]
 [0.01980235 0.40593876 0.69247104 0.81739136 0.00338041]
 [0.19216718 0.5822993  0.48964517 0.48392417 0.96564601]]
matriks mI1Random:
 [89 54 63 78 71 24 54 83 53 68]
matriks mI2Random:
 [[76 19 52 51]
 [13 55 75 49]
 [28 46 70 77]
 [42 87 71  3]]


In [41]:
#Aritmatic Array
x = np.array([1,2,3])
y = np.array([4,5,6])
r1 = np.dot(x,y)
r2 = np.add(x,y)
r3 = np.dot(x,3)
print(f"Hasil perkalian dot product : {r1}")
print(f"Hasil penjumlahan matriks :\n{r2}")
print(f"Hasil dot prodct dengan 3:\n{r3}")

Hasil perkalian dot product : 32
Hasil penjumlahan matriks :
[5 7 9]
Hasil dot prodct dengan 3:
[3 6 9]


In [49]:
#fungsi statistk dasar
nilaiPemrograman = np.array([100,90,80,80,50,50,50,40])
nilaiMin = np.min(nilaiPemrograman)
nilaiMax = np.max(nilaiPemrograman)
nilaiMean = np.mean(nilaiPemrograman)
nilaiSum = np.sum(nilaiPemrograman)
nilaiMedian = np.median(nilaiPemrograman)
nilaiStd = np.std(nilaiPemrograman)

print(f"Nilai Pemrograman:\n{nilaiPemrograman}")
print(f"Nilai terkecil:\n{nilaiMin}")
print(f"Nilai terbesar:\n{nilaiMax}")
print(f"Nilai rata-rata:\n{nilaiMean}")
print(f"Total nilai:\n{nilaiSum}")
print(f"Nilai tengah:\n{nilaiMedian}")
print(f"Nilai Deviasi\n{nilaiStd}")

dataLulus = nilaiPemrograman [nilaiPemrograman > 50]
print(dataLulus)
print(f"jumllah mahasiswa yang lulus :{dataLulus.size}")

Nilai Pemrograman:
[100  90  80  80  50  50  50  40]
Nilai terkecil:
40
Nilai terbesar:
100
Nilai rata-rata:
67.5
Total nilai:
540
Nilai tengah:
65.0
Nilai Deviasi
21.065374432940896
[100  90  80  80]
jumllah mahasiswa yang lulus :4
